[env:m5stack-core2]
platform = espressif32@^6.5.0
board = m5stack-core2
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = spiffs

lib_deps =
    m5stack/M5Unified@^0.2.0
    bblanchon/ArduinoJson@^7.0.4

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -O2
